apiVersion: v1
kind: Service
metadata:
  name: tracy-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracy-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tracy-server
